language: python

cache: pip

python:
    - "2.7_with_system_site_packages"

before_install:
    - sudo apt-get update -qq
    - if [[ $TRAVIS_PYTHON_VERSION == *"2."* ]]; then sudo apt-get install python-numpy; fi
    - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran

install:
    - pip install -U pip wheel
    - pip install -r requirements.txt

script:
    - py.test -v
